config/routes.rb
class RestrictedListConstraint
    
  def initialize
    @allowed_subdomains = ['superadmin', 'verizoncoin-env-4', 'verizoncoin-env-4.us-east-1']
    @allowed_subdomains << 'ngrok.io' if Rails.env.development?
    
    puts "INITIALIZED"
  end
  
  def matches?(request)
    puts "REQUEST SUBDOMAIN - #{request.subdomain}"
    if Rails.env.development?
      request.domain == 'localhost' || request.domain == 'ngrok.io'
    else
      @allowed_subdomains.include?(request.subdomain)
    end
  end

end

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  constraints RestrictedListConstraint.new do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    devise_for :super_users, :skip => [:registrations]
    namespace :admin do
      resources :coins
      resources :transfers
      resources :users
      resources :contacts
      root to: 'coins#index'
      get '/reports', to: 'reports#index', as: 'reports_path'
      get '/reports/send_daily_update', to: 'reports#send_daily_update', as: 'daily_update'
      get 'transfers/:id/edit_images', to: 'transfers#edit_images'
      post 'transfers/:id/rotate', to: 'transfers#rotate'
    end

    get '/reminders/current_users', to: 'reminders#current_users'
    get '/reports/all_transfers', to: 'reports#all_transfers'
    get '/reports/transfers_past_seven', to: 'reports#transfers_past_seven'
    get '/reports/days_since', to: 'reports#days_since', as: 'days_since'
    get '/reports/users', to: 'reports#users'
    
    resources :reminders, only: [:create]

  end

  get '/coins/filters', to: 'coins#filters'
  get '/coins/vz_web', to: 'coins#vz_web'
  get '/coins/:id/vz_web', to: 'coins#vz_web_show'
  get '/users/vz_web', to: 'users#vz_web_show'

  get '/coins/all_transfers', to: 'coins#all_transfers', as: 'all_transfers'
  
  resources :transfers
  post 'transfers/:id/upload_file', to: 'transfers#upload_file', as: 'upload_file'
  get '/active_owners', to: 'transfers#active_owners', as: 'active_owners'
  get '/vz_active_owners', to: 'transfers#vz_active_owners', as: 'vz_active_owners'
  get '/transfer_report', to: 'transfers#transfer_report', as: 'transfer_report'
  get '/vz_transfer_report', to: 'transfers#vz_transfer_report', as: 'vz_transfer_report'
  get '/activityfeed', to: 'transfers#activityfeed', as: 'activityfeed'
  get '/stats', to: 'transfers#stats', as: 'stats'

  resources :coins
  post '/coins/update_owner', to: 'coins#update_owner', as: 'update_owner'
  get '/coins/:id/transfers', to: 'coins#transfers', as: 'coin_transfers'
  get '/coins/test_error', to: 'coins#test_error', as: 'test_error'

  resources :users
  get '/user_by_email', to: 'users#user_by_email', as: 'user_by_email'
  get 'first_names', to: 'users#first_name', as: 'users_first_name'

  resources :contacts
  root :to => redirect('/admin/coins')
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user
  # belongs_to :transfer, through: :user
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def current_users
    query_string = <<-HEREDOC
    select t.id, t.user_id, t.coin_id
    from (
      select coin_id, max(created_at) as maxcreated_at 
      from transfers group by coin_id
    ) as x inner join transfers as t on t.coin_id = x.coin_id and t.created_at = x.maxcreated_at;
    HEREDOC




    res = ActiveRecord::Base.connection.execute(query_string)

    if params[:filter] == '1'
      new_query = ActiveRecord::Base.connection.execute(
        <<~HEREDOC
          select * from users
          WHERE id in (#{res.pluck("id").join(",")})
          AND NOT EXISTS (
              SELECT 1 FROM reminders
              WHERE reminders.user_id = users.id
          )
          HEREDOC
      )
      @transfers = Transfer.where({id: res.pluck("id")}).joins(:user).where('transfers.user_id in (?)', new_query.pluck('id')).order(created_at: 'asc').paginate(page: params[:page], per_page: 30)
      @filtered = true
    else 
      @transfers = Transfer.where({id: res.pluck("id")}).left_joins(:user).order(created_at: 'asc').paginate(page: params[:page], per_page: 30)
    end
    
    render 'current_users'

  end

  def index
    @reminders = Reminder.all
  end

  def create
    user_id = params["reminder"]["user_id"]
    if !user_id
      raise "no user id provided"
    end

    user = User.find(user_id)

    mailer_res = UserNotifierMailer.send_days_left_email(user).deliver_now
    
    if !mailer_res
      puts mailer_res
      raise 'Error sending'
    end

    if mailer_res
      @reminder = Reminder.new({user: user})
    end

    respond_to do |format|
      if @reminder.save
        format.html {
          redirect_back(fallback_location: root_path)
        }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:user_id)
    end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% reminder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/current_users.erb
<div id="main-nav">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div id="menu-icon" data-active="false">
      
    </div>
    <div class="navbar-brand">
      <a href="/">
        <%= image_tag 'logo-white.png' %>
      </a>
    </div>
  </nav>
</div>



<div class="table-responsive">
  <div class='flex-header-row'>

    <h1 class='main-content__page-title' id='reminders-top-thing'>Reminders</h1>

    <ul class='vz-tab-list'>
      <li class="vz-tab-li " id="tab_7g9tyi" role="presentation">
        <a href='/reminders/current_users'>
          <button class="<%= @filtered ? 'vz-tab-btn' : 'vz-selected-tab-btn' %>">
              <span>
                All
              </span>
            </span>
          </button>
        </a>
      </li>
      <li class="vz-tab-li" id="tab_hpbq35" role="presentation">
        <a href='/reminders/current_users?filter=1'>
          <button class="<%= @filtered ? 'vz-selected-tab-btn' : 'vz-tab-btn' %>">
            <span>
              Not Sent
            </span>
          </button>
        </a>
      </li>
    </ul>

  </div>


  <table class='table' style="width:100%">
    <thead>
      <tr>
        <th>email</th>
        <th>first name</th>
        <th>Days Left</th>
        <th>Transfer Date</th>
        <th>Sent Reminder?</th>
        <th>Reminder sent on</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @transfers.each do |transfer| %>
        <% user = transfer.user %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= transfer.days_left %>
          <td><%= transfer.created_at.strftime("%Y/%m/%d") %>
          <td><%= user.reminders.any? %>
          <% if user.reminders.last %>
            <td>
              <%= user.reminders.last.created_at.strftime("%Y/%m/%d") %>
            </td>
          <% else %>
            <td>
            </td>
          <% end %>
          <td>
            <%= form_with(model: Reminder.new, local: true, data: { confirm: "Are you sure you want to send a reminder to #{user.first_name}?" }) do |form| %>
              <%= form.hidden_field :user_id, value: user.id %>
              <%= form.submit value: 'submit'  %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class='pagination-cont'>
<%= will_paginate @transfers %>
</div>

<script>
 $('form').on('click', function handleSubmit (event) {
   event.preventDefault()
   if (window.confirm(event.currentTarget.dataset.confirm)) {
     $(this).submit();
   }
 })
</script>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.user_id %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reminder.user_id %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>