config/routes.rb
class RestrictedListConstraint
    
  def initialize
    @allowed_subdomains = ['superadmin', 'verizoncoin-env-4', 'verizoncoin-env-4.us-east-1']
    @allowed_subdomains << 'ngrok.io' if Rails.env.development?
    
    puts "INITIALIZED"
  end
  
  def matches?(request)
    puts "REQUEST SUBDOMAIN - #{request.subdomain}"
    if Rails.env.development?
      request.domain == 'localhost' || request.domain == 'ngrok.io'
    else
      @allowed_subdomains.include?(request.subdomain)
    end
  end

end

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  constraints RestrictedListConstraint.new do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    devise_for :super_users, :skip => [:registrations]
    namespace :admin do
      resources :coins
      resources :transfers
      resources :users
      resources :contacts
      root to: 'coins#index'
      get '/reports', to: 'reports#index', as: 'reports_path'
      get '/reports/send_daily_update', to: 'reports#send_daily_update', as: 'daily_update'
      get 'transfers/:id/edit_images', to: 'transfers#edit_images'
      post 'transfers/:id/rotate', to: 'transfers#rotate'
    end

    get '/reminders/current_users', to: 'reminders#current_users'
    get '/reports/all_transfers', to: 'reports#all_transfers'
    get '/reports/transfers_past_seven', to: 'reports#transfers_past_seven'
    get '/reports/days_since', to: 'reports#days_since', as: 'days_since'
    get '/reports/users', to: 'reports#users'
    
    resources :reminders, only: [:create]

  end

  get '/coins/filters', to: 'coins#filters'
  get '/coins/vz_web', to: 'coins#vz_web'
  get '/coins/:id/vz_web', to: 'coins#vz_web_show'
  get '/users/vz_web', to: 'users#vz_web_show'

  get '/coins/all_transfers', to: 'coins#all_transfers', as: 'all_transfers'
  
  resources :transfers
  post 'transfers/:id/upload_file', to: 'transfers#upload_file', as: 'upload_file'
  get '/active_owners', to: 'transfers#active_owners', as: 'active_owners'
  get '/vz_active_owners', to: 'transfers#vz_active_owners', as: 'vz_active_owners'
  get '/transfer_report', to: 'transfers#transfer_report', as: 'transfer_report'
  get '/vz_transfer_report', to: 'transfers#vz_transfer_report', as: 'vz_transfer_report'
  get '/activityfeed', to: 'transfers#activityfeed', as: 'activityfeed'
  get '/stats', to: 'transfers#stats', as: 'stats'

  resources :coins
  post '/coins/update_owner', to: 'coins#update_owner', as: 'update_owner'
  get '/coins/:id/transfers', to: 'coins#transfers', as: 'coin_transfers'
  get '/coins/test_error', to: 'coins#test_error', as: 'test_error'

  resources :users
  get '/user_by_email', to: 'users#user_by_email', as: 'user_by_email'
  get 'first_names', to: 'users#first_name', as: 'users_first_name'

  resources :contacts
  root :to => redirect('/admin/coins')
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transfers, dependent: :delete_all
  has_many :coins, through: :transfers
  has_many :reminders, dependent: :destroy
  validates_presence_of :email
  RESULT_TYPES = ["administrative_area_level_1", "locality"]
  
  has_person_name

  def coin
    coins.try(:first)
  end

  def only_one_coin
    if self.coins.length > 1
      errors.add(:name, "user is already associated with a coin")
    end
  end

  def fetch_location_data
    search = Geocoder.search(self.zip)
    found_data = search[0].data["address"] rescue nil

    if self.city || self.state
      return
    end
    
    if !self.zip || !self.latitude
      return
    end


    
    fetch_str = ""
    if self.zip
      fetch_str = "https://maps.googleapis.com/maps/api/geocode/json?address=#{self.zip}&result_type=#{RESULT_TYPES.join("|")}&key=#{Rails.application.credentials.google_api_key}"
    else
      fetch_str = "https://maps.googleapis.com/maps/api/geocode/json?latlng=#{self.latitude},#{self.longitude}&result_type=#{RESULT_TYPES.join("|")}&key=#{ENV["GOOGLE_API_KEY"]}"
    end

    response = HTTParty.get(fetch_str)

    city = nil
    state = nil

    has_results = response["results"][0]["address_components"] rescue nil
    
    if !has_results
      return
    end

    update_params = {}

    response["results"][0]["address_components"].each {|ac|
      if ac["types"].include?("administrative_area_level_1")
        state = ac["short_name"] || ac["long_name"]
        update_params[:state] = state
      end
      if ac["types"].include?("locality")
        city = ac["long_name"] || ac["short_name"]
        update_params[:city] = city
      end
    }

    self.update(update_params)

  end  
  
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_super_user!, only: [:create, :show, :destroy]
  skip_before_action :verify_authenticity_token
  LETTERS = [ 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z' ]

  def first_name
    render json: User.select(:first_name).limit(100).order(id: :asc).pluck(:first_name)
  end

  def index
    @users = User.all
  end

  def vz_web_show
    authenticate_vz_web_call
    if !LETTERS.include?(params[:letter])
      render json: {message: 'forbidden'}, status: 403
      return
    end
    @users = User.where("regexp_replace(last_name, '^.* ', '') ILIKE ?", "#{params[:letter]}%")
                 .order("regexp_replace(last_name, '^.* ', '')")
                 .eager_load(:coins, :transfers)
    render '/users/index_vz_web'
  end

  def user_by_email
    @user = User.where("lower(email) = ?", params[:email].downcase).first
    @coin = Coin.where('number', params[:coin])
    if @user
      # if session[:current_coin].present?
        render "users/show.json", status: :ok
    else
      render json: "user not found", status: :not_found
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :location)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <% if current_super_user.admin? %>
        <th>Email</th>
      <% end %>
      <th>First name</th>
      <th>Last name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <% if current_super_user.admin? %>
          <td><%= user.email %></td>
        <% end %>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }</td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_super_user.admin? %>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
<% end %>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>