config/routes.rb
class RestrictedListConstraint
    
  def initialize
    @allowed_subdomains = ['superadmin', 'verizoncoin-env-4', 'verizoncoin-env-4.us-east-1']
    @allowed_subdomains << 'ngrok.io' if Rails.env.development?
    
    puts "INITIALIZED"
  end
  
  def matches?(request)
    puts "REQUEST SUBDOMAIN - #{request.subdomain}"
    if Rails.env.development?
      request.domain == 'localhost' || request.domain == 'ngrok.io'
    else
      @allowed_subdomains.include?(request.subdomain)
    end
  end

end

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  constraints RestrictedListConstraint.new do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    devise_for :super_users, :skip => [:registrations]
    namespace :admin do
      resources :coins
      resources :transfers
      resources :users
      resources :contacts
      root to: 'coins#index'
      get '/reports', to: 'reports#index', as: 'reports_path'
      get '/reports/send_daily_update', to: 'reports#send_daily_update', as: 'daily_update'
      get 'transfers/:id/edit_images', to: 'transfers#edit_images'
      post 'transfers/:id/rotate', to: 'transfers#rotate'
    end

    get '/reminders/current_users', to: 'reminders#current_users'
    get '/reports/all_transfers', to: 'reports#all_transfers'
    get '/reports/transfers_past_seven', to: 'reports#transfers_past_seven'
    get '/reports/days_since', to: 'reports#days_since', as: 'days_since'
    get '/reports/users', to: 'reports#users'
    
    resources :reminders, only: [:create]

  end

  get '/coins/filters', to: 'coins#filters'
  get '/coins/vz_web', to: 'coins#vz_web'
  get '/coins/:id/vz_web', to: 'coins#vz_web_show'
  get '/users/vz_web', to: 'users#vz_web_show'

  get '/coins/all_transfers', to: 'coins#all_transfers', as: 'all_transfers'
  
  resources :transfers
  post 'transfers/:id/upload_file', to: 'transfers#upload_file', as: 'upload_file'
  get '/active_owners', to: 'transfers#active_owners', as: 'active_owners'
  get '/vz_active_owners', to: 'transfers#vz_active_owners', as: 'vz_active_owners'
  get '/transfer_report', to: 'transfers#transfer_report', as: 'transfer_report'
  get '/vz_transfer_report', to: 'transfers#vz_transfer_report', as: 'vz_transfer_report'
  get '/activityfeed', to: 'transfers#activityfeed', as: 'activityfeed'
  get '/stats', to: 'transfers#stats', as: 'stats'

  resources :coins
  post '/coins/update_owner', to: 'coins#update_owner', as: 'update_owner'
  get '/coins/:id/transfers', to: 'coins#transfers', as: 'coin_transfers'
  get '/coins/test_error', to: 'coins#test_error', as: 'test_error'

  resources :users
  get '/user_by_email', to: 'users#user_by_email', as: 'user_by_email'
  get 'first_names', to: 'users#first_name', as: 'users_first_name'

  resources :contacts
  root :to => redirect('/admin/coins')
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_super_user!

    # def authenticate_admin
      # TODO Add authentication logic here.
    # end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
    def valid_action?(name, resource = resource_class)
      if ['destroy', 'edit'].include?(name.to_s) && !current_super_user.admin?
        return false
      end
      !!routes.detect do |controller, action|
        controller == resource.to_s.underscore.pluralize && action == name.to_s
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  class ForbiddenError < StandardError
  end

  rescue_from ApplicationController::ForbiddenError do |exception|
    head :forbidden
  end

  def authenticate_super_user_unless_json
    authenticate_super_user! unless request.format.json?
  end

  def authenticate_vz_web_call
    Rails.logger.info("------")
    Rails.logger.info("request domain auth vz web ---- #{request.headers['origin']}")
    Rails.logger.info("------") 
    unless params[:secret_key] && params[:secret_key] == "967efb08b60f3555d8bc"
      raise ForbiddenError
    end
    true
  end

  def check_for_coin
    @user = User.find(session[:current_coin])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <% unless !current_super_user.admin? && attr_name.to_s == 'email' %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
        <% end %>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                 <% unless !current_super_user.admin? && attribute.attribute.to_s == 'email' %>
                  <%= attribute.attribute.to_s == 'verified' ? (resource.verified ? 'Yes' : 'No') : render_field(attribute) %>
                <% end %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if page.resource_name == 'coin' -%>
    <div class="field-unit field-unit--user">    
      <div class="field-unit__label">
        <label for="coin_number">User Email</label>
      </div>
      <div class="field-unit__field">
        <input type="email" name="coin[user_email]" value="<%= page.resource&.owner&.email %>">
      </div>
    </div>
  <% end -%>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/application/_icons.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="icon-cancel" viewBox="0 0 48 48">
    <path fill-rule="evenodd" d="M24 19.757l-8.485-8.485c-.784-.783-2.047-.782-2.827 0l-1.417 1.416c-.777.777-.78 2.046.002 2.827L19.757 24l-8.485 8.485c-.783.784-.782 2.047 0 2.827l1.416 1.417c.777.777 2.046.78 2.827-.002L24 28.243l8.485 8.485c.784.783 2.047.782 2.827 0l1.417-1.416c.777-.777.78-2.046-.002-2.827L28.243 24l8.485-8.485c.783-.784.782-2.047 0-2.827l-1.416-1.417c-.777-.777-2.046-.78-2.827.002L24 19.757zM24 47c12.703 0 23-10.297 23-23S36.703 1 24 1 1 11.297 1 24s10.297 23 23 23z" />
  </symbol>

  <symbol id="icon-eyeglass" viewBox="0 0 48 48">
    <path d="M27.885 32.515c-2.864 1.966-6.333 3.116-10.07 3.116C7.976 35.63 0 27.656 0 17.817 0 7.976 7.976 0 17.816 0S35.63 7.976 35.63 17.816c0 3.736-1.15 7.205-3.115 10.07l14.53 14.53c1.278 1.277 1.275 3.352 0 4.628-1.28 1.278-3.353 1.278-4.63 0l-14.53-14.53zm-10.07-3.736c6.056 0 10.964-4.91 10.964-10.964 0-6.055-4.91-10.964-10.964-10.964-6.055 0-10.964 4.91-10.964 10.964 0 6.055 4.91 10.963 10.964 10.963z" />
  </symbol>

  <symbol id="icon-up-caret" viewBox="0 0 48 48">
    <path d="M2.988 33.02c-1.66 0-1.943-.81-.618-1.824l20-15.28c.878-.672 2.31-.67 3.188 0l20.075 15.288c1.316 1.003 1.048 1.816-.62 1.816H2.987z" />
  </symbol>
</svg>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
<%= link_to("Analytics", stats_path(), class: 'navigation__link navigation__link--inactive') %>
  <% Administrate::Namespace.new('admin').resources.each do |resource| %>
    <%= link_to(
      ['contacts', 'reports'].include?(resource.name.to_s) ? {contacts: 'Support Requests', reports: 'Reports' }[resource.name.to_sym] : display_resource_name(resource),
      resource.name.to_s == 'reports' ? '/admin/reports' : [namespace, resource_index_route_key(resource)],
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) %>
  <% end %>


<%= link_to("Activity Feed", activityfeed_path(@activity), class: 'navigation__link navigation__link--inactive') %>
<%= link_to("Send Reminder", '/reminders/current_users?filter=1', class: 'navigation__link navigation__link--inactive') %>

<% if super_user_signed_in? %>
  <%= link_to('Logout', destroy_super_user_session_path, method: :delete) %>
<% else %>
    <%= link_to('Login', new_super_user_session_path) %>
<% end %>

</nav>

app/views/admin/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>

<style>
.pt-2 {
  padding-top: 2rem;
}

.flex-row-col {
  display: flex;
  flex-direction: column;
}

.image-row {
  display: flex;
  flex-direction: row;
  margin: 1rem;
}

.image-row > * {
  margin: 1rem;
  flex: 1 0 0;
}

.edit-controls {
  background-color: aliceblue;
  width: 130px;
  display: flex;
  padding: 1rem;
  flex-direction: column;
  align-items: center; 
  justify-content: center;
}

.edit-controls > * {
  padding: 1rem;
}

</style>

app/views/admin/application/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: page.resource_name.titleize.downcase
      ),
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/application/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <% unless !current_super_user.admin? && attribute.attribute.to_s == 'email' %>
        <dt class="attribute-label" id="<%= attribute.name %>">
        <%= t(
          "helpers.label.#{resource_name}.#{attribute.name}",
          default: attribute.name.titleize,
        ) %>
        </dt>
        <dd class="attribute-data attribute-data--<%=attribute.html_class%>">
            <%= render_field attribute, page: page %>
        </dd>
      <% end %>
    <% end %>
  </dl>
</section>