config/routes.rb
class RestrictedListConstraint
    
  def initialize
    @allowed_subdomains = ['superadmin', 'verizoncoin-env-4', 'verizoncoin-env-4.us-east-1']
    @allowed_subdomains << 'ngrok.io' if Rails.env.development?
    
    puts "INITIALIZED"
  end
  
  def matches?(request)
    puts "REQUEST SUBDOMAIN - #{request.subdomain}"
    if Rails.env.development?
      request.domain == 'localhost' || request.domain == 'ngrok.io'
    else
      @allowed_subdomains.include?(request.subdomain)
    end
  end

end

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  constraints RestrictedListConstraint.new do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    devise_for :super_users, :skip => [:registrations]
    namespace :admin do
      resources :coins
      resources :transfers
      resources :users
      resources :contacts
      root to: 'coins#index'
      get '/reports', to: 'reports#index', as: 'reports_path'
      get '/reports/send_daily_update', to: 'reports#send_daily_update', as: 'daily_update'
      get 'transfers/:id/edit_images', to: 'transfers#edit_images'
      post 'transfers/:id/rotate', to: 'transfers#rotate'
    end

    get '/reminders/current_users', to: 'reminders#current_users'
    get '/reports/all_transfers', to: 'reports#all_transfers'
    get '/reports/transfers_past_seven', to: 'reports#transfers_past_seven'
    get '/reports/days_since', to: 'reports#days_since', as: 'days_since'
    get '/reports/users', to: 'reports#users'
    
    resources :reminders, only: [:create]

  end

  get '/coins/filters', to: 'coins#filters'
  get '/coins/vz_web', to: 'coins#vz_web'
  get '/coins/:id/vz_web', to: 'coins#vz_web_show'
  get '/users/vz_web', to: 'users#vz_web_show'

  get '/coins/all_transfers', to: 'coins#all_transfers', as: 'all_transfers'
  
  resources :transfers
  post 'transfers/:id/upload_file', to: 'transfers#upload_file', as: 'upload_file'
  get '/active_owners', to: 'transfers#active_owners', as: 'active_owners'
  get '/vz_active_owners', to: 'transfers#vz_active_owners', as: 'vz_active_owners'
  get '/transfer_report', to: 'transfers#transfer_report', as: 'transfer_report'
  get '/vz_transfer_report', to: 'transfers#vz_transfer_report', as: 'vz_transfer_report'
  get '/activityfeed', to: 'transfers#activityfeed', as: 'activityfeed'
  get '/stats', to: 'transfers#stats', as: 'stats'

  resources :coins
  post '/coins/update_owner', to: 'coins#update_owner', as: 'update_owner'
  get '/coins/:id/transfers', to: 'coins#transfers', as: 'coin_transfers'
  get '/coins/test_error', to: 'coins#test_error', as: 'test_error'

  resources :users
  get '/user_by_email', to: 'users#user_by_email', as: 'user_by_email'
  get 'first_names', to: 'users#first_name', as: 'users_first_name'

  resources :contacts
  root :to => redirect('/admin/coins')
end

app/models/transfer.rb
require 'csv'

class Transfer < ApplicationRecord
  TRANSFER_ATTRS = ['coin_number', 'user_first_name', 'user_last_name', 'user_email', 'user_zip', 'giver_first_name', 'giver_email', 'notes', 'transfer_date']
  belongs_to :user
  belongs_to :coin
  validate :only_one_coin, if: :should_validate?
  validate :not_same_user, if: :should_validate?
  validate :is_coin_owner, if: :should_validate?
  has_many_attached :files
  has_many :reminders, through: :user





  def self.all_transfers_query
    <<~SQL
    SELECT c.number as coin_number,
    u.first_name as user_first_name, u.last_name as user_last_name, u.email as user_email, u.zip as user_zip, 
    g.first_name as giver_first_name, g.last_name as giver_last_name, g.email as giver_email,
    t.notes as notes, t.created_at as transfer_date
    FROM transfers as t
    LEFT JOIN coins as c on t.coin_id = c.id
    LEFT JOIN users AS u ON t.user_id = u.id
    LEFT JOIN users as g on t.giver_id = g.id
    ORDER BY coin_number ASC, transfer_date;
    SQL
  end

  def self.all_transfers_csv
    results = ActiveRecord::Base.connection.execute(all_transfers_query)
    attrs = TRANSFER_ATTRS
    CSV.generate(headers: true) do |csv|
      csv << attrs

      results.each do |tuple|
        csv << TRANSFER_ATTRS.map {|attr| tuple[attr] }
      end
    end
  end  

  def should_validate?
    new_record?
  end
  
  def user_full_name
    if self.user
      "#{self.user.first_name} #{self.user.last_name}" 
    else 
      ""
    end
  end

  def only_one_coin
    if self.user.coins.length >= 1
      errors.add(:transfer, "user already has a coin, select another user")
    end
  end

  def self.as_csv
    attrs = Transfer.new.attributes.keys
    CSV.generate(headers: true) do |csv|
      csv << attrs

      Transfer.find_each do |t|
        csv << attrs.map {|attr| t.send(attr.to_sym) }
      end
    end
  end

  def self.active_owners
    latest_transfers = Transfer.select('DISTINCT ON ("coin_id") *').order(:coin_id, created_at: :desc)
    latest_transfers.map do |transfer|
      user = transfer.user
      user.as_json.merge({
        "received" => transfer.created_at.in_time_zone('Eastern Time (US & Canada)'),
        "days_left" => transfer.days_left,
        "coin_number" => transfer.coin&.display_number,
        "notes" => transfer.notes
      })
    end
  end

  def self.active_owners_as_csv
    active_owners = self.active_owners
    attributes = ["id", "first_name","last_name", "email", "received", "days_left", "coin_number", "zip", "notes"]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      active_owners.each do |owner|
        csv << attributes.map{ |attr| owner[attr] }
      end
    end
  end

  def self.vz_active_owners_as_csv
    active_owners = self.active_owners
    attributes = ["id", "first_name","last_name", "email", "received", "days_left", "coin_number", "zip", "notes"]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      active_owners.each do |owner|
        if owner['email'].include? 'verizon'
          csv << attributes.map{ |attr| owner[attr] }
        end
      end
    end
  end

  def self.transfer_report_as_csv
    transfers = []
    Coin.find_each do |coin|
      coin.transfers.each.with_index do |transfer, idx|
         unless idx == 0
            user = transfer.user
            transfers.push({
              'id': transfer.id,
              'coin_id': transfer.coin_id,
              'coin_number': transfer.coin.try(:number),
              'created_at': transfer.created_at,
              'first_name': user.try(:first_name),
              'last_name': user.try(:last_name),
              'notes': transfer.try(:notes),
              'zip': user.try(:zip),
              'email': user.try(:email)})
          end
       end
    end
    attributes = ["id", "coin_id", "coin_number", "created_at", "first_name", "last_name", "notes", "zip", "email"]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      transfers.each do |item|
        csv << [item[:id], item[:coin_id], item[:coin_number], item[:created_at], item[:first_name], item[:last_name], item[:notes], item[:zip], item[:email]]
      end
    end
  end

  def self.vz_transfer_report_as_csv
    transfers = []
    Coin.find_each do |coin|
      coin.transfers.each.with_index do |transfer, idx|
         unless idx == 0
            user = transfer.user
            if user.try(:email).include? 'verizon'
              transfers.push({
                'id': transfer.id,
                'coin_id': transfer.coin_id,
                'coin_number': transfer.coin.try(:number),
                'created_at': transfer.created_at,
                'first_name': user.try(:first_name),
                'last_name': user.try(:last_name),
                'notes': transfer.try(:notes),
                'zip': user.try(:zip),
                'email': user.try(:email)
              })
            end
          end
       end
    end
    attributes = ["id", "coin_id", "coin_number", "created_at", "first_name", "last_name", "notes", "zip", "email"]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      transfers.each do |item|
        csv << [item[:id], item[:coin_id], item[:coin_number], item[:created_at], item[:first_name], item[:last_name], item[:notes], item[:zip], item[:email]]
      end
    end
  end

  def not_same_user
    if self.coin.owner === self.user
      errors.add(:transfer, "you can't transfer the coin to yourself")
    end
  end

  def is_coin_owner
    #should verify that the owner is the giver
  end

  def giver_vz
    User.select(:first_name, :last_name).where(id: self.giver_id).first
  end

  def user_vz
    User.select(:first_name, :last_name, :city, :state).where(id: self.user_id).first
  end

  def days_left
    begin
      days_passed = (((self.created_at.beginning_of_day + 60.days) - Time.now.beginning_of_day) / 86400).ceil
      if days_passed <= 0
        return 0
      end
      days_passed
    rescue
      nil
    end
  end

  def days_left_leader
    begin
      days_passed = (((self.created_at.beginning_of_day + 63.days) - Time.now.beginning_of_day) / 86400).ceil
      if days_passed <= 0
        return 0
      end
      days_passed
    rescue
      nil
    end
  end

end

app/controllers/admin/transfers_controller.rb
module Admin
  class TransfersController < Admin::ApplicationController
    skip_before_action :verify_authenticity_token, only: [:rotate]
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end
    def edit_images
      @transfer = Transfer.find(params[:id])
      render layout: '/admin/application'
    end

    def rotate
      degree = params[:degree]
      @transfer = Transfer.find(params[:id])
      RotateJob.new.perform(@transfer.id, degree.to_i)
      redirect_back(fallback_location: root_path)
    end    

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_super_user!, except: [:create, :upload_file]
  before_action :set_cors_headers, only: [:update]
  skip_before_action :verify_authenticity_token

  include Rails.application.routes.url_helpers

  def set_cors_headers

  end

  def index
    @transfers = Transfer.all
    respond_to do |format|
      format.html { render 'tranfers/index' }
      format.csv { send_data Transfer.as_csv }
    end
  end

  def show
  end

  def new
    @transfer = Transfer.new
  end

  def edit
  end

  def activityfeed
    transfers = Transfer.joins("left join users on user_id = users.id").select('transfers.*, users.id, users.first_name').order('created_at DESC')
    transfers_with_givers = transfers.joins('left join users as givers on transfers.giver_id = givers.id left join coins on transfers.coin_id=coins.id')
                                     .select("transfers.id as id, CONCAT(givers.first_name,' ', givers.last_name) as giver_name, coins.number as coin_number")
    @activity = transfers_with_givers
    @markers = User.where("latitude IS NOT NULL AND longitude IS NOT NULL").pluck('latitude', 'longitude', 'first_name', 'id')
  end

  def stats
    transfers = Transfer.joins("left join users on user_id = users.id").select('transfers.*, users.id, users.first_name').order('created_at DESC')
    transfers_with_givers = transfers.joins('left join users as givers on transfers.giver_id = givers.id').select('transfers.id as id, givers.first_name as giver_name')
    @totalTransfers = transfers_with_givers
    # @totalToday = Transfer.where("created_at >= ?", Time.zone.now.beginning_of_day)
    @totalToday = Transfer.where("created_at >= ?", Date.today)
    @totalYesterday = Transfer.where("DATE(created_at) = ?", Date.today-1)
    @passedOnce = Transfer.group(:coin_id).distinct.having('count(coin_id) = 1').count.count
    @passedTwice = Transfer.group(:coin_id).distinct.having('count(coin_id) = 2').count.count
    @passedThreeOrMore = Transfer.group(:coin_id).distinct.having('count(coin_id) > 3').count.count
  end

  def active_owners

    respond_to do |format|
      format.csv {
        send_data Transfer.active_owners_as_csv
      }
      format.html {
        @active_owners = Transfer.active_owners
        render 'transfers/active_owners'
      }
    end
  end

  def vz_active_owners
    respond_to do |format|
      format.csv {
        send_data Transfer.vz_active_owners_as_csv
      }
    end
  end

  def transfer_report
    respond_to do |format|
      format.csv {
        send_data Transfer.transfer_report_as_csv
      }
    end
  end

  def vz_transfer_report
    respond_to do |format|
      format.csv {
        send_data Transfer.vz_transfer_report_as_csv
      }
    end
  end

  def create
    user = User.where("lower(email) = ?", params[:email].downcase).first

    unless user
      user = User.new({
        first_name: params[:first_name],
        last_name: params[:last_name],
        email: params[:email].downcase
      })

      unless user.save
        render json: @user.errors, status: :unprocessable_entity
        return
      end

    end

    coin = Coin.find_by(id: params[:coin_id])

    unless coin
      render json: "coin not found", status: :unprocessable_entity
      return
    end

    @transfer = Transfer.new({
      giver_id: coin.owner.id,
      user: user,
      coin: coin,
      notes: params[:notes]
    })

    respond_to do |format|
      if @transfer.save
        UserNotifierMailer.send_transfer_notification_email(@transfer).deliver_now
        
        coin.users.where.not(id: [@transfer.giver_id, user.id]).find_each {|previous_owner|
          UserNotifierMailer.send_previous_user_notification_email(@transfer, previous_owner).deliver_later
        }
        
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_file
    @transfer = Transfer.find_by(id: params[:id])
    if @transfer.files.attach(params[:files])
      render json: rails_blob_path(@transfer.files.first, disposition: "attachment", only_path: true), status: :ok
    else
      render json: @transfer.errors, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    def transfer_params
      params.require(:transfer).permit(:notes, :user_id, :coin_id)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_with(model: transfer, local: true) do |form| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
        <% transfer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :giver_id %>
    <%= form.text_field :giver_id %>
  </div>  

  <div class="field">
    <%= form.label :coin_id %>
    <%= form.text_field :coin_id %>
  </div>
    
  <div class="field">
    <%= form.label :files %>
    <%= form.file_field :files %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transfers/active_owners.erb
<div class='section'>
  <table class="table">
  <thead>
    <th>user id</th>
    <th>first name</th>
    <th>last name</th>
    <th>email</th>
    <th>received</th>
    <th>days left</th>
  </thead>
  <tbody>
  <% @active_owners.each do |active_owner| %>
    <tr>
      <td><%= active_owner["id"] %></td>
      <td><%= active_owner["first_name"] %></td>
      <td><%= active_owner["last_name"] %></td>
      <td><%= active_owner["email"] %></td>
      <td><%= active_owner["received"] %></td>
      <td><%= active_owner["days_left"] %></td>
    </tr>
  <% end %>
  </tbody>
  

</div>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>User</th>
      <th>Coin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.notes %></td>
        <td><%= transfer.user_id %></td>
        <td><%= transfer.coin_id %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' }</td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @transfer.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @transfer.user_id %>
</p>

<p>
  <strong>Coin:</strong>
  <%= @transfer.coin_id %>
</p>

<%= link_to 'edit images', edit_images_path(@transfer) %>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/stats.html.erb
<div id="activity-feed-nav">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div id="menu-icon" data-active="false">
      <div class="open">
        <%= image_tag 'HamburgerIcon.png' %>
      </div>
      <div class="close hidden">
        <%= image_tag 'menuiconclose.png' %>
      </div>
      <div id="main-menu" class="hidden">
        <nav class="navigation" role="navigation">
        <%= link_to("Analytics", stats_path(), class: 'navigation__link navigation__link--active') %>

        <%= link_to("Coins", admin_coins_path(), class: 'navigation__link navigation__link--inactive') %>

        <%= link_to("Transfers", admin_transfers_path(), class: 'navigation__link navigation__link--inactive') %>

        <%= link_to("Users", admin_users_path(), class: 'navigation__link navigation__link--inactive') %>

        <%= link_to("Reports", '/admin/reports', class: 'navigation__link navigation__link--inactive') %>

        <%= link_to("Support Requests", admin_contacts_path(), class: 'navigation__link navigation__link--inactive') %>

        <%= link_to("Activity Feed", activityfeed_path(@activity), class: 'navigation__link navigation__link--inactive') %>
        </nav>
      </div>
    </div>
    <div class="navbar-brand">
      <a href="/">
        <%= image_tag 'logo-white.png' %>
      </a>
    </div>
  </nav>
</div>

<div id="stats" class="m0auto fixed-width">
  <div id="all-stats">
    <div class="stat-title">
      Purpose Coin Analytics
    </div>
    <hr>
    <div class="coin-activity p-3">
      <div class="stat-sub-title mb-4">
        Purpose Coin Activity
      </div>
      <div class="coin-activity-data columns is-mobile">
        <div class="column">
          <span class="stat-number"><%= @totalToday.length %></span>
          <br>
          <span>today</span>
        </div>
        <div class="column">
          <span class="stat-number"><%= @totalYesterday.length %></span>
          <br>
          <span>yesterday</span>
        </div>
        <div class="column">
          <span class="stat-number"><%= @totalTransfers.length %></span>
          <br>
          <span>total</span>
        </div>
      </div>
    </div>
    <div class="coin-activity p-3 white blackbg">
      <div class="stat-sub-title mb-4">
        Purpose Coin Transfers
      </div>
      <div class="coin-activity-data columns is-mobile">
        <div class="column">
          <span class="stat-number"><%= @passedOnce %></span>
          <br>
          <span>1 transfer</span>
        </div>
        <div class="column">
          <span class="stat-number"><%= @passedTwice %></span>
          <br>
          <span>2 transfers</span>
        </div>
        <div class="column">
          <span class="stat-number"><%= @passedThreeOrMore %></span>
          <br>
          <span>3+ transfers</span>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('#menu-icon').on('click', function() {
      var active = $(this).data('active');
      if(active === 'true'){
        $('#main-menu').addClass('hidden');
        $('#menu-icon .close').addClass('hidden');
        $('#menu-icon .open').removeClass('hidden');
        $(this).data('active', 'false');
      } else {
        $('#main-menu').removeClass('hidden')
        $('#menu-icon .close').removeClass('hidden');
        $('#menu-icon .open').addClass('hidden');
        $(this).data('active', 'true');
      }
    });
  })
</script>